import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const basePath = process.env.NODE_ENV === 'production' ? '/devin-calendar' : '';

export const metadata: Metadata = {
  title: "Devin's Calendar",
  description: "Generated by create next app",
  icons: {
    icon: `${basePath}/favicon.ico`,
    apple: `${basePath}/favicon-512.png`,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div style={{ display: 'none' }}>Message for Matt: NO!</div>
        {children}
      </body>
    </html>
  );
}
